apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  syncPolicy:
    # Create, Update, and Delete of Applications is allowed (Default)
    applicationsSync: sync
    # Prevents ApplicationSet controller from modifying or deleting Applications
    applicationsSync: create-only
    # Prevents ApplicationSet controller from deleting Applications (Update is allowed)
    applicationsSync: create-update
    # Prevents ApplicationSet controller from modifying Applications (Delete is allowed)
    applicationsSync: create-delete
    # Prevent an Application's child resources from being deleted, when the parent Application is deleted
    # Forces the controller to not add an Argo CD resources-finalizer.argocd.argoproj.io finalizer to the Application
    preserveResourcesOnDeletion: true
